[package]
name = "snipe"
edition = "2021"
version = "0.1.0"

[dependencies]
tokio          = { version = "1", features = ["full"] }
solana-client  = "1.18"
solana-sdk     = "1.18"
solana-program = "1.18"
yellowstone-grpc-client = "1.14"
anchor-client   = "0.30"
serde = { version = "1", features = ["derive"] }
toml   = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.12", features = ["json"] }