rpc_http   = "https://nl.rpc.asuga.io/"
grpc_addr  = "https://nl.grpc.asuga.io:10000/"
grpc_x_token = "YOUR_0SLOT_KEY"

# Telegram & Discord
tg_token   = "7675187926:AAF19_J0yLnIVzgRiV1vRuZO-G1X_YXHDKw"
tg_chat    = "@topsolsniper1_bot"
discord_webhook = "https://discord.com/api/webhooks/..."

# Snipe params
amount_sol = 0.2            # how much SOL per snipe
slippage_bps = 500          # 5 %
priority_fee_microlamports = 100_000

# Exit rules
trail_up_50_sl = true       # 50 % → set SL = entry
stop_loss_pct = 65          # if never hit 50 %
take_profit_pct = 400       # 5 x = 400 % gain